// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rfq.Infrastructure;

#nullable disable

namespace Rfq.Infrastructure.Migrations
{
    [DbContext(typeof(RfqDbContext))]
    [Migration("20260921012841_AddInitialRevisionConfirm")]
    partial class AddInitialRevisionConfirm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("rfq_case_id_seq");

            modelBuilder.Entity("Rfq.Infrastructure.CaseCurrentEntity", b =>
                {
                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<string>("AssignedTraderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_trader_id");

                    b.Property<string>("ContactOwnerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_owner_id");

                    b.Property<Guid>("CurrentRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_revision_id");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("lifecycle");

                    b.Property<bool>("Owned")
                        .HasColumnType("boolean")
                        .HasColumnName("owned");

                    b.Property<string>("QuoteRequestReason")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("quote_request_reason");

                    b.Property<string>("QuoteStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("quote_status");

                    b.Property<string>("RfqStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rfq_status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("CaseId");

                    b.HasIndex("CurrentRevisionId");

                    b.ToTable("case_currents", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.CategoryEntity", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.CategoryRoutingEntity", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<string>("DefaultTraderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("default_trader_id");

                    b.HasKey("CategoryId");

                    b.HasIndex("DefaultTraderId");

                    b.ToTable("category_routings", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.ClientEntity", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("ClientId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_code");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.DeskEntity", b =>
                {
                    b.Property<string>("DeskId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("desk_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("DeskId");

                    b.ToTable("desks", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.MasterUserEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("DeskId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("desk_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.HasKey("UserId");

                    b.HasIndex("DeskId");

                    b.ToTable("master_users", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqCaseEntity", b =>
                {
                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<string>("CategorySnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_snapshot");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("SalesId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sales_id");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_id");

                    b.HasKey("CaseId");

                    b.HasIndex("SalesId", "CreatedAt")
                        .HasDatabaseName("ix_rfq_cases_sales_id_created_at");

                    b.ToTable("rfq_cases", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqRevisionEntity", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("Notional")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("notional");

                    b.Property<string>("SalesAndTradingMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sales_and_trading_message");

                    b.Property<DateOnly?>("SettlementDate")
                        .HasColumnType("date")
                        .HasColumnName("settlement_date");

                    b.Property<DateOnly>("StandardSettlementDate")
                        .HasColumnType("date")
                        .HasColumnName("standard_settlement_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("RevisionId");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_rfq_revisions_one_draft_per_case")
                        .HasFilter("status = 'Draft'");

                    b.ToTable("rfq_revisions", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.SecurityEntity", b =>
                {
                    b.Property<string>("SecurityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_id");

                    b.Property<string>("BbgDisplay")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bbg_display");

                    b.Property<string>("BbgSearchText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bbg_search_text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("internal_code");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("isin");

                    b.Property<string>("JapaneseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("japanese_name");

                    b.HasKey("SecurityId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InternalCode")
                        .IsUnique()
                        .HasDatabaseName("ux_securities_internal_code");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasDatabaseName("ux_securities_isin");

                    b.ToTable("securities", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.SeedMarker", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.HasKey("Key");

                    b.ToTable("seed_markers", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.BusinessDateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.HasKey("Key");

                    b.ToTable("business_dates", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.WorkingQuoteEntity", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("RevisionId");

                    b.ToTable("working_quotes", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.CaseCurrentEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqCaseEntity", "RfqCase")
                        .WithOne("Current")
                        .HasForeignKey("Rfq.Infrastructure.CaseCurrentEntity", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rfq.Infrastructure.RfqRevisionEntity", "CurrentRevision")
                        .WithMany()
                        .HasForeignKey("CurrentRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentRevision");

                    b.Navigation("RfqCase");
                });

            modelBuilder.Entity("Rfq.Infrastructure.CategoryRoutingEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.CategoryEntity", null)
                        .WithOne()
                        .HasForeignKey("Rfq.Infrastructure.CategoryRoutingEntity", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rfq.Infrastructure.MasterUserEntity", null)
                        .WithMany()
                        .HasForeignKey("DefaultTraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Rfq.Infrastructure.MasterUserEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.DeskEntity", null)
                        .WithMany()
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqRevisionEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqCaseEntity", "RfqCase")
                        .WithMany("Revisions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RfqCase");
                });

            modelBuilder.Entity("Rfq.Infrastructure.SecurityEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Rfq.Infrastructure.WorkingQuoteEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqRevisionEntity", "Revision")
                        .WithOne()
                        .HasForeignKey("Rfq.Infrastructure.WorkingQuoteEntity", "RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqCaseEntity", b =>
                {
                    b.Navigation("Current")
                        .IsRequired();

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
