// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rfq.Infrastructure;

#nullable disable

namespace Rfq.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RfqDbContext))]
    [Migration("20260922110108_AddPostProcessBusinessDates")]
    partial class AddPostProcessBusinessDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("rfq_case_id_seq");

            modelBuilder.Entity("Rfq.Infrastructure.BusinessDateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.HasKey("Key");

                    b.ToTable("business_dates", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.CalculationFailureLogEntity", b =>
                {
                    b.Property<Guid>("FailureLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("failure_log_id");

                    b.Property<decimal>("AttemptedValue")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("attempted_value");

                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("driver");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PriorWorkingQuoteJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("prior_working_quote");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<decimal>("SimpleYieldSlide")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("simple_yield_slide");

                    b.Property<string>("TraderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trader_id");

                    b.HasKey("FailureLogId");

                    b.HasIndex("RevisionId");

                    b.HasIndex("CaseId", "OccurredAt")
                        .HasDatabaseName("ix_calculation_failure_logs_case_id_occurred_at");

                    b.ToTable("calculation_failure_logs", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.CaseCurrentEntity", b =>
                {
                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<string>("AssignedTraderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_trader_id");

                    b.Property<DateOnly?>("ClosedBusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("closed_business_date");

                    b.Property<Guid?>("ClosedQuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_quote_id");

                    b.Property<string>("ContactOwnerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_owner_id");

                    b.Property<Guid?>("CurrentQuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_quote_id");

                    b.Property<Guid>("CurrentRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_revision_id");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("lifecycle");

                    b.Property<bool>("Owned")
                        .HasColumnType("boolean")
                        .HasColumnName("owned");

                    b.Property<string>("QuoteRequestReason")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("quote_request_reason");

                    b.Property<string>("QuoteStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("quote_status");

                    b.Property<string>("RfqStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rfq_status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("CaseId");

                    b.HasIndex("ClosedQuoteId");

                    b.HasIndex("CurrentQuoteId");

                    b.HasIndex("CurrentRevisionId");

                    b.HasIndex("RfqStatus")
                        .HasDatabaseName("ix_case_currents_rfq_status");

                    b.ToTable("case_currents", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.CategoryEntity", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.CategoryRoutingEntity", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<string>("DefaultTraderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("default_trader_id");

                    b.HasKey("CategoryId");

                    b.HasIndex("DefaultTraderId");

                    b.ToTable("category_routings", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.ClientEntity", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("ClientId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_code");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.ConfirmedQuoteEntity", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("CalculatedPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("calculated_payload");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int?>("ExpiryMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("expiry_minutes");

                    b.Property<string>("ManualPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("manual_payload");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mode");

                    b.Property<string>("RequestReasonAnswered")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("request_reason_answered");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_id");

                    b.Property<DateOnly>("SettlementDate")
                        .HasColumnType("date")
                        .HasColumnName("settlement_date");

                    b.HasKey("QuoteId");

                    b.HasIndex("RevisionId", "ConfirmedAt")
                        .HasDatabaseName("ix_confirmed_quotes_revision_id_confirmed_at");

                    b.ToTable("confirmed_quotes", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.DeskEntity", b =>
                {
                    b.Property<string>("DeskId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("desk_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("DeskId");

                    b.ToTable("desks", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.EventCursorEntity", b =>
                {
                    b.Property<string>("CursorKey")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cursor_key");

                    b.Property<long>("LastEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_event_id");

                    b.HasKey("CursorKey");

                    b.ToTable("event_cursors", (string)null);

                    b.HasData(
                        new
                        {
                            CursorKey = "global",
                            LastEventId = 0L
                        });
                });

            modelBuilder.Entity("Rfq.Infrastructure.EventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("EventId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.MasterUserEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<int?>("DefaultQuoteExpiryMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("default_quote_expiry_minutes");

                    b.Property<string>("DefaultQuoteMode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_quote_mode");

                    b.Property<string>("DeskId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("desk_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.HasKey("UserId");

                    b.HasIndex("DeskId");

                    b.ToTable("master_users", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.QuoteEventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("EventId");

                    b.HasIndex("QuoteId");

                    b.ToTable("quote_events", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqCaseEntity", b =>
                {
                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<string>("CategorySnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_snapshot");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<long?>("CopiedFromCaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("copied_from_case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("CreatedBusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("created_business_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("SalesId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sales_id");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_id");

                    b.HasKey("CaseId");

                    b.HasIndex("CopiedFromCaseId");

                    b.HasIndex("CreatedBusinessDate")
                        .HasDatabaseName("ix_rfq_cases_created_business_date");

                    b.HasIndex("SalesId", "CreatedAt")
                        .HasDatabaseName("ix_rfq_cases_sales_id_created_at");

                    b.ToTable("rfq_cases", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqEventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<DateOnly?>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("EventId");

                    b.HasIndex("CaseId");

                    b.HasIndex("BusinessDate", "Type")
                        .HasDatabaseName("ix_rfq_events_business_date_type");

                    b.ToTable("rfq_events", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqRevisionEntity", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("confirmed_by");

                    b.Property<Guid?>("CopiedFromRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("copied_from_revision_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("Notional")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("notional");

                    b.Property<Guid?>("QuoteSeedRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_seed_revision_id");

                    b.Property<string>("SalesAndTradingMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sales_and_trading_message");

                    b.Property<DateOnly?>("SettlementDate")
                        .HasColumnType("date")
                        .HasColumnName("settlement_date");

                    b.Property<DateOnly>("StandardSettlementDate")
                        .HasColumnType("date")
                        .HasColumnName("standard_settlement_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("RevisionId");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_rfq_revisions_one_draft_per_case")
                        .HasFilter("status = 'Draft'");

                    b.HasIndex("CopiedFromRevisionId");

                    b.HasIndex("QuoteSeedRevisionId");

                    b.ToTable("rfq_revisions", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.SalesMemoEntity", b =>
                {
                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("CaseId");

                    b.ToTable("sales_memos", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.SecurityEntity", b =>
                {
                    b.Property<string>("SecurityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_id");

                    b.Property<string>("BbgDisplay")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bbg_display");

                    b.Property<string>("BbgSearchText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bbg_search_text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("internal_code");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("isin");

                    b.Property<string>("JapaneseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("japanese_name");

                    b.HasKey("SecurityId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InternalCode")
                        .IsUnique()
                        .HasDatabaseName("ux_securities_internal_code");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasDatabaseName("ux_securities_isin");

                    b.ToTable("securities", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.SeedMarker", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.HasKey("Key");

                    b.ToTable("seed_markers", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.TraderMemoEntity", b =>
                {
                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("CaseId");

                    b.ToTable("trader_memos", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.UserGridConfigEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("ScreenId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("screen_id");

                    b.Property<string>("ConfigKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("UserId", "ScreenId", "ConfigKey");

                    b.ToTable("user_grid_configs", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.WorkingQuoteEntity", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<string>("CalculatedPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("calculated_payload");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("ManualPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("manual_payload");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("RevisionId");

                    b.ToTable("working_quotes", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.CalculationFailureLogEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqCaseEntity", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rfq.Infrastructure.RfqRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rfq.Infrastructure.CaseCurrentEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqCaseEntity", "RfqCase")
                        .WithOne("Current")
                        .HasForeignKey("Rfq.Infrastructure.CaseCurrentEntity", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rfq.Infrastructure.ConfirmedQuoteEntity", "ClosedQuote")
                        .WithMany()
                        .HasForeignKey("ClosedQuoteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Rfq.Infrastructure.ConfirmedQuoteEntity", "CurrentQuote")
                        .WithMany()
                        .HasForeignKey("CurrentQuoteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Rfq.Infrastructure.RfqRevisionEntity", "CurrentRevision")
                        .WithMany()
                        .HasForeignKey("CurrentRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClosedQuote");

                    b.Navigation("CurrentQuote");

                    b.Navigation("CurrentRevision");

                    b.Navigation("RfqCase");
                });

            modelBuilder.Entity("Rfq.Infrastructure.CategoryRoutingEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.CategoryEntity", null)
                        .WithOne()
                        .HasForeignKey("Rfq.Infrastructure.CategoryRoutingEntity", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rfq.Infrastructure.MasterUserEntity", null)
                        .WithMany()
                        .HasForeignKey("DefaultTraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Rfq.Infrastructure.ConfirmedQuoteEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqRevisionEntity", "Revision")
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Rfq.Infrastructure.MasterUserEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.DeskEntity", null)
                        .WithMany()
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Rfq.Infrastructure.QuoteEventEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.EventEntity", "Event")
                        .WithOne()
                        .HasForeignKey("Rfq.Infrastructure.QuoteEventEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rfq.Infrastructure.ConfirmedQuoteEntity", null)
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqCaseEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqCaseEntity", null)
                        .WithMany()
                        .HasForeignKey("CopiedFromCaseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqEventEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqCaseEntity", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rfq.Infrastructure.EventEntity", "Event")
                        .WithOne()
                        .HasForeignKey("Rfq.Infrastructure.RfqEventEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqRevisionEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqCaseEntity", "RfqCase")
                        .WithMany("Revisions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rfq.Infrastructure.RfqRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("CopiedFromRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Rfq.Infrastructure.RfqRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("QuoteSeedRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RfqCase");
                });

            modelBuilder.Entity("Rfq.Infrastructure.SalesMemoEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqCaseEntity", "RfqCase")
                        .WithOne("SalesMemo")
                        .HasForeignKey("Rfq.Infrastructure.SalesMemoEntity", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RfqCase");
                });

            modelBuilder.Entity("Rfq.Infrastructure.SecurityEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Rfq.Infrastructure.TraderMemoEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqCaseEntity", "RfqCase")
                        .WithOne("TraderMemo")
                        .HasForeignKey("Rfq.Infrastructure.TraderMemoEntity", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RfqCase");
                });

            modelBuilder.Entity("Rfq.Infrastructure.WorkingQuoteEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqRevisionEntity", "Revision")
                        .WithOne()
                        .HasForeignKey("Rfq.Infrastructure.WorkingQuoteEntity", "RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqCaseEntity", b =>
                {
                    b.Navigation("Current")
                        .IsRequired();

                    b.Navigation("Revisions");

                    b.Navigation("SalesMemo")
                        .IsRequired();

                    b.Navigation("TraderMemo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
