// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rfq.Infrastructure;

#nullable disable

namespace Rfq.Infrastructure.Migrations
{
    [DbContext(typeof(RfqDbContext))]
    [Migration("20260921000401_UseIncrementalCaseId")]
    partial class UseIncrementalCaseId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("rfq_case_id_seq");

            modelBuilder.Entity("Rfq.Infrastructure.CaseCurrentEntity", b =>
                {
                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<Guid>("CurrentRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_revision_id");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("lifecycle");

                    b.Property<string>("RfqStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rfq_status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("CaseId");

                    b.HasIndex("CurrentRevisionId");

                    b.ToTable("case_currents", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqCaseEntity", b =>
                {
                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("SalesId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sales_id");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_id");

                    b.HasKey("CaseId");

                    b.HasIndex("SalesId", "CreatedAt")
                        .HasDatabaseName("ix_rfq_cases_sales_id_created_at");

                    b.ToTable("rfq_cases", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqRevisionEntity", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("RevisionId");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_rfq_revisions_one_draft_per_case")
                        .HasFilter("status = 'Draft'");

                    b.ToTable("rfq_revisions", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.SeedMarker", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.HasKey("Key");

                    b.ToTable("seed_markers", (string)null);
                });

            modelBuilder.Entity("Rfq.Infrastructure.CaseCurrentEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqCaseEntity", "RfqCase")
                        .WithOne("Current")
                        .HasForeignKey("Rfq.Infrastructure.CaseCurrentEntity", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rfq.Infrastructure.RfqRevisionEntity", "CurrentRevision")
                        .WithMany()
                        .HasForeignKey("CurrentRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentRevision");

                    b.Navigation("RfqCase");
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqRevisionEntity", b =>
                {
                    b.HasOne("Rfq.Infrastructure.RfqCaseEntity", "RfqCase")
                        .WithMany("Revisions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RfqCase");
                });

            modelBuilder.Entity("Rfq.Infrastructure.RfqCaseEntity", b =>
                {
                    b.Navigation("Current")
                        .IsRequired();

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
